---
- name: Remove Service Catalog Broker service
  oc_obj:
    state: absent
    namespace: "{{ openshift_service_catalog_broker_namespace }}"
    kind: service
    name: ups-broker

- name: Remove Service Catalog Broker deployment
  oc_obj:
    state: absent
    namespace: "{{ openshift_service_catalog_broker_namespace }}"
    kind: deployment
    name: ups-broker

- name: Remove Service Catalog Broker namespace
  oc_project:
    state: absent
    name: "{{ openshift_service_catalog_broker_namespace }}"
