---
# do any asserts here

- name: Create temp directory for doing work in
  command: mktemp -d /tmp/openshift-logging-ansible-XXXXXX
  register: mktemp
  changed_when: False

## static pod for api server
- name: Create pod definition directory
  file:
    name: "{{ openshift_service_catalog_pod_definition_dir }}"
    state: directory
    permissions: 0755

- name: Create pod definition in directory
  template:
    src: api_server.j2
    dest: "{{ openshift_service_catalog_pod_definition_dir }}/service_catalog_api_server.yml"
  vars:
    image: ""
    namespace: ""
    cpu_limit: none
    memory_limit: none
    cpu_requests: none
    memory_request: none
    cors_allowed_origin: localhost

# Necessary to update kubelet config and restart?

## controller process DC
- name: Create Controller definition
  template:
    src: controller_dc.j2
    dest: "{{ mktemp.stdout }}/controller_dc.yml"
  vars:
    image: ""
    replicas: 1
    node_selector: ""
    cpu_limit: none
    memory_limit: none

- name: Set Controller DC
  oc_obj:
    name: service-catalog-controller
    namespace: openshift-infra
    kind: dc
    state: present
    files:
    - "{{ mktemp.stdout }}/controller_dc.yml"
    delete_after: yes

- name: Scale up Controller
  oc_scale:
    name: service-catalog-controller
    namespace: openshift-infra
    kind: dc
    replicas: "{{ openshift_service_catalog_replicas | default(1) }}"

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
