---

## static pod for api server
- name: Create pod definition directory
  file:
    name: "{{ openshift_service_catalog_pod_definition_dir }}"
    state: directory
    permissions: 0755

- name: Copy pod definition to directory
  copy:
    src: api_server.yml
    dest: "{{ openshift_service_catalog_pod_definition_dir }}/service_catalog_api_server.yml"

# Necessary to update kubelet config and restart?

## controller process DC
- name: Copy Controller definition
  copy:
    src: controller_dc.yml
    dest: "{{ tempdir }}/controller_dc.yml"

- name: Set Controller DC
  oc_obj:
    name: service-catalog-controller
    state: present
    namespace: openshift-infra
    files:
    - "{{ tempdir }}/controller_dc.yml"
    delete_after: yes
