---
## static pod for api server
- name: Create pod definition directory
  file:
    name: "{{ openshift_service_catalog_pod_definition_dir }}"
    state: directory
    permissions: 0755

- name: Remove pod definition from directory
  file:
    path: "{{ openshift_service_catalog_pod_definition_dir }}/service_catalog_api_server.yml"
    state: absent

- name: Remove Controller DC
  oc_obj:
    name: service-catalog-controller
    state: absent
    namespace: openshift-infra
    kind: dc
