---
- name: Remove Service Catalog API Server route
  oc_obj:
    state: absent
    namespace: "{{ openshift_service_catalog_namespace }}"
    kind: route
    name: apiserver

- name: Remove Service Catalog API Server service
  oc_obj:
    state: absent
    namespace: "{{ openshift_service_catalog_namespace }}"
    kind: service
    name: apiserver

- name: Remove Service Catalog API Server deployment
  oc_obj:
    state: absent
    namespace: "{{ openshift_service_catalog_namespace }}"
    kind: deployment
    name: apiserver

- name: Remove Controller Manager service
  oc_obj:
    state: absent
    namespace: "{{ openshift_service_catalog_namespace }}"
    kind: service
    name: controller-manager

- name: Remove Controller Manager deployment
  oc_obj:
    state: absent
    namespace: "{{ openshift_service_catalog_namespace }}"
    kind: deployment
    name: controller-manager

- name: Remove Service Catalog namespace
  oc_project:
    state: absent
    name: "{{ openshift_service_catalog_namespace }}"
